# Makefile for emg_servo_control

CXX = g++
CXXFLAGS = -Wall -std=c++11
LDFLAGS = -lwiringPi

TARGET = emg_servo_control
OBJECTS = emg_servo_control.o

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) $(OBJECTS) -o $(TARGET) $(LDFLAGS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS) $(TARGET)
